package br.gov.es.infoplan.config.spo;

public class SPOPentahoConfigKey {
    public static final String VLR_AUTORIZADO = "vlr_autorizado";
    public static final String UO = "uo";
    public static final String COD_UO = "cod_uo";
    public static final String ANO = "ano";
    public static final String PO = "po";
    public static final String COD_PO = "cod_po";
    public static final String NOME_PO = "nome_po";
    public static final String NOME = "nome";
    public static final String NOME_UO = "nome_uo";
    public static final String COD_ACAO = "cod_acao";
    public static final String NOME_ACAO = "nom_acao";
    public static final String COD_FONTE = "cod_fonte";
    public static final String NOME_FONTE = "nome_fonte";
    public static final String SIGLA = "sigla";
    public static final String VLR_PREVISTO = "vlr_previsto";
    public static final String VLR_CONTRATADO = "vlr_contratado";
    public static final String VLR_EMPENHADO = "vlr_empenhado";
    public static final String VLR_LIQUIDADO = "vlr_liquidado";
    public static final String VLR_PAGO_COM_RAP = "vlr_pago_com_rap";
    public static final String VLR_SEM_RAP = "vlr_pago_sem_rap";
    public static final String VLR_PAGO = "vlr_pago";
    public static final String DT_FIM_EXTRACAO = "dt_fim_extracao";
    public static final String DISPONIVEL_SEM_RESERVA = "disponivel_sem_reserva";
    public static final String DISPONIVEL = "disponivel";
    public static final String DISPONIVEL_COM_RESERVA = "disponivel_com_reserva";
    public static final String EMPENHADO_A_LIQUIDAR = "empenhado_a_liquidar";
    public static final String SUCCESS_PLANNED = "sucesso";
    public static final String COMPARATIVE = "comparativo";
    public static final String LIQUIDATED = "liquidado";
    public static final String PAID = "pago";
    public static final String FEASIBILITY = "exequibilidade";
    public static final String MISSION = "missao";
    public static final String CHANGE = "alteracao";
    public static final String IGO = "IGO";
    public static final String COMMITTED = "empenhado";
    public static final String COMMITTED_BAR_AUTHORIZED = "empenhado/autorizado";
    public static final String LIQUIDATED_BAR_AUTHORIZED = "liquidado/autorizado";
    public static final String AUTHORIZED = "autorizado";
    public static final String BUDGETED = "orcado";
    public static final String COD_GND = "cod_gnd";
    public static final String NAME_GND = "nome_gnd";
}
