package br.gov.es.infoplan.config.pentahoBi;

public class PentahoBiConfigKeys {
    public static final String SPO_TOTAL_AUTORIZADO_UO = "planejamentoOrcamentarioTotalAutorizadoUo";
    public static final String SPO_TOTAL_AUTORIZADO_PO = "planejamentoOrcamentarioTotalAutorizadoPo";
    public static final String SPO_TOTAL_ANO = "planejamentoOrcamentarioTotalAno";
    public static final String SPO_TOTAL_ANO_SIGEFES = "planejamentoOrcamentarioTotalAnoSigefes";
    public static final String INDICATOR_EXECUTION_UO_BY_YEAR = "indicadorExecucaoUOPorAno";
    public static final String INDICATOR_EXECUTION_SEARCH_ACTION = "indicadorExecucaoBuscarAcao";
    public static final String INDICATOR_EXECUTION_SEARCH_FULL_SOURCE = "indicadorExecucaoBuscarFonteCompleta";
    public static final String INDICATOR_EXECUTION_CARD_SEM_RESERVA = "indicadorExecucaoCardDisponivelSemReserva";
    public static final String INDICATOR_EXECUTION_CARD_SUCESSO =  "indicadorExecucaoCardSucesso";
    public static final String INDICATOR_EXECUTION_CARD_COMPARATIVO = "indicadorExecucaoCardComparativo";
    public static final String INDICATOR_EXECUTION_CARD_PO_COM_MAIOR_LIQUIDADO = "indicadorExecucaoCardPOComMaiorLiquidado";
    public static final String INDICATOR_EXECUTION_CARD_EXEQUIBILIDADE = "indicadorExecucaoCardExequibilidade";
    public static final String INDICATOR_EXECUTION_CARD_MISSAO = "indicadorExecucaoCardMissao";
    public static final String INDICATOR_EXECUTION_CARD_ALTERACAO = "indicadorExecucaoCardAlteracao";
    public static final String INDICATOR_EXECUTION_CARD_IGO = "indicadorExecucaoCardIGO";
    public static final String INDICATOR_EXECUTION_DASH_AVAILABILITY_TO_UO = "indicadorExecucaoDashDisponivelPorUo";
    public static final String INDICATOR_EXECUTION_DASH_SUCCESS_OF_PLANNED = "indicadorExecucaoDashSucessoDoPlanejado";
    public static final String INDICATOR_EXECUTION_DASH_PLANNED_BUDGETARY = "indicadorExecucaoDashPlanejamentoOrcamentario";
    public static final String PAINEL_OBRAS_FILTRO_ORGAO = "painelObrasFiltroOrgao";
    public static final String PAINEL_OBRAS_FILTRO_MUNICIPIO = "painelObrasFiltroMunicipio";
    public static final String PAINEL_OBRAS_FILTRO_STATUS = "painelObrasFiltroStatus";
    public static final String PAINEL_OBRAS_TOTAL_PROGRMAS = "painelObrasTotalProgramas";
    public static final String PAINEL_OBRAS_TOTAL_PROJETOS = "painelObrasTotalProjetos";
    public static final String PAINEL_OBRAS_TOTAL_REALIZADO = "painelObrasTotalRealizado";
    public static final String PAINEL_OBRAS_TOTAL_PLANEJADO = "painelObrasTotalPlanejado";
    public static final String PAINEL_OBRAS_TOTAL_CONTAGEM_PE = "painelObrasTotalContagemPE";
    public static final String PAINEL_OBRAS_TOTAL_CONTAGEM_ENTREGAS = "painelObrasTotalContagemEntregas";
    public static final String PAINEL_OBRAS_QUANTIDADE_POR_STATUS = "painelObrasQuantidadePorStatus";
    public static final String PAINEL_OBRAS_TOTAL_ENTREGAS_POR_ANO_E_STATUS = "painelObrasTotalEntregasPorAnoEStatus";
    public static final String PAINEL_OBRAS_TOTAL_ENTREGAS_ORGAO = "painelObrasTotalEntregasPorOrgao";
    public static final String PAINEL_OBRAS_TOTAL_ENTREGAS_ORGAO_EXECEUCAO = "painelObrasTotalEntregasPorOrgaoExecucao";
    public static final String PAINEL_OBRAS_TOTAL_ENTREGAS_MUNICIPIO_STATUS = "painelObrasTotalMunicipioStatus";
    public static final String PAINEL_OBRAS_NUMERO_ENTREGAS_POR_STATUS = "painelObrasNumeroEntregasPorStatus";
    public static final String PAINEL_OBRAS_TOTAL_ENTREGAS_POR_MES_CARTEIRA = "painelObrasTotalEntregasPorMesCarteira";
    public static final String PAINEL_OBRAS_QUANTIDADE_MAIOR_PREVISTA_CARTEIRA = "painelObrasQuantidadeMaiorPrevistaCarteira";
    public static final String PAINEL_OBRAS_QUANTIDADE_MAIOR_MUNICIPIO_CARTEIRA = "painelObrasQuantidadeMaiorMunicipioCarteira";
}
